---

name: FORD Documentation for OptaDOS
author:  Felix Mildner modified from Jim Madge
description: Build documentation for OptaDOS using FORD
inputs:
  project_file:
    description: Name of the directory to call "make ford" in
    default: /optados/
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project_file }}
branding:
  icon: book
  color: orange
