---

name: FORD Documentation
author: Jim Madge - modified by Felix Mildner
description: Build documentation for a Fortran project using FORD
inputs:
  project_file:
    description: Name of the FORD project file
    required: true
    default: project-file.md
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.project_file }}
branding:
  icon: book
  color: orange
